SELECT event_statistics_row_id, file_id, base_filename, cat_prcsg_dt, trd_dt, sbmtr_id, cat_rprtr_imid, cat_rprtr_org_id, acptd_rjctd_ind, third_party_id, actn_type, event_type_cd, prdct_type, ttl_rcrds, late_acptd_rcrds, rprd_rcrds, create_ts, update_ts
	FROM im_owner.event_statistics where prdct_type is null;


SELECT 
CAT_RPRTR_IMID, 
SBMTR_ID, 
COALESCE(NULLIF(EVENT_TYPE_CD,''),'N/A') EVENT_TYPE_CD, 
SUM(TTL_RCRDS) PROCESSED, 
SUM(CASE WHEN ACPTD_RJCTD_IND = 'A' THEN TTL_RCRDS ELSE 0 END) ACCEPTED, 
SUM(LATE_ACPTD_RCRDS) ACCEPTED_LATE, 
SUM(CASE WHEN ACPTD_RJCTD_IND = 'R' THEN TTL_RCRDS ELSE 0 END) REJECTED, 
SUM(CASE WHEN ACPTD_RJCTD_IND = 'A' AND ACTN_TYPE = 'COR' THEN TTL_RCRDS ELSE 0 END) PROCESSED_CORRECTIONS, 
SUM(CASE WHEN ACPTD_RJCTD_IND = 'A' AND ACTN_TYPE = 'RPR' THEN TTL_RCRDS ELSE 0 END) PROCESSED_REPAIRED, 
SUM(CASE WHEN ACPTD_RJCTD_IND = 'A' AND ACTN_TYPE = 'DEL' THEN TTL_RCRDS ELSE 0 END) PROCESSED_DELETED 
FROM  
IM_OWNER.EVENT_STATISTICS 
WHERE  CAT_PRCSG_DT = '2020-01-17' AND CAT_RPRTR_ORG_ID = '79'
GROUP BY 
CAT_RPRTR_IMID, 
SBMTR_ID, 
COALESCE(NULLIF(EVENT_TYPE_CD,''),'N/A') order by CAT_RPRTR_IMID