SELECT upl_bus_objct_bdata_id, upload_user_name, bucket_name, s3_prefix, base_filename, filename, upload_source, upl_file_size_bytes, process_date, upload_org_id, submitter_id, reporter_id, derived_reporter_crd, upload_timestamp, acknowledge_bdata_id, acknowledge_create_ts, acknowledge_result, integrity_bdata_id, integrity_result, associated_meta_file_bdata_id, associated_meta_file_usage_cd, associated_upl_meta_file_bdata_id, integrity_timeout_warn_usage_cd, integrity_timeout_warn_bdata_id, integrity_timeout_error_usage_cd, integrity_timeout_error_bdata_id, integrity_duplicate_usage_cd, integrity_duplicate_bdata_id, integrity_start_ts, integrity_end_ts, ingestion_bdata_id, ingestion_accepted_records, ingestion_rejected_records, ingestion_total_records, ingestion_process_mode, ingestion_result, ingestion_start_ts, ingestion_end_ts, full_file_reject
	FROM im_owner.file_status_data where submitter_id='79' and process_date='2020-01-07' and reporter_id='BBC';
	
select sum(ingestion_rejected_records) FROM im_owner.file_status_data where upl_bus_objct_bdata_id in (2423693, 2167728)

SELECT upl_bus_objct_bdata_id, upload_user_name, bucket_name, s3_prefix, base_filename, filename, upload_source, upl_file_size_bytes, process_date, upload_org_id, submitter_id, reporter_id, derived_reporter_crd, upload_timestamp, acknowledge_bdata_id, acknowledge_create_ts, acknowledge_result, integrity_bdata_id, integrity_result, associated_meta_file_bdata_id, associated_meta_file_usage_cd, associated_upl_meta_file_bdata_id, integrity_timeout_warn_usage_cd, integrity_timeout_warn_bdata_id, integrity_timeout_error_usage_cd, integrity_timeout_error_bdata_id, integrity_duplicate_usage_cd, integrity_duplicate_bdata_id, integrity_start_ts, integrity_end_ts, ingestion_bdata_id, ingestion_accepted_records, ingestion_rejected_records, ingestion_total_records, ingestion_process_mode, ingestion_result, ingestion_start_ts, ingestion_end_ts, full_file_reject
	FROM im_owner.file_status_data where submitter_id is null;
	
SELECT upl_bus_objct_bdata_id, upload_user_name, bucket_name, s3_prefix, base_filename, filename, upload_source, upl_file_size_bytes, process_date, upload_org_id, submitter_id, reporter_id, derived_reporter_crd, upload_timestamp, acknowledge_bdata_id, acknowledge_create_ts, acknowledge_result, integrity_bdata_id, integrity_result, associated_meta_file_bdata_id, associated_meta_file_usage_cd, associated_upl_meta_file_bdata_id, integrity_timeout_warn_usage_cd, integrity_timeout_warn_bdata_id, integrity_timeout_error_usage_cd, integrity_timeout_error_bdata_id, integrity_duplicate_usage_cd, integrity_duplicate_bdata_id, integrity_start_ts, integrity_end_ts, ingestion_bdata_id, ingestion_accepted_records, ingestion_rejected_records, ingestion_total_records, ingestion_process_mode, ingestion_result, ingestion_start_ts, ingestion_end_ts, full_file_reject
	FROM im_owner.file_status_data where submitter_id is not null and reporter_id is null;